DATASETS:
  TRAIN:
  - train
  TEST:
  - val
INPUT:
  FORMAT: RGB
  COCO_VAL_PATH: /home/grisha/piece_train/dataset/val2017
  MIN_SIZE_TEST: 384
MODEL:
  META_ARCHITECTURE: 'LocalizerAndClassifier'
  PIXEL_MEAN: [123.675, 123.675, 123.675]
  PIXEL_STD: [65.025, 65.025, 65.025]
  LAC:
    DETECTOR:
      MODULE: 'ssd.ssd'
      TYPE: 'SSD'
      INPUT_SIZE: (512, 512)
      CFG:
        MODEL:
          BACKBONE:
            NAME: "build_mobilenet_backbone"
            PRETRAINED: True
          SSD:
              NUM_CLASSES: 1
              NUM_CONVS: 0
              IN_FEATURES: ["feat1", "feat2"]
              SCORE_THRESH_TEST: 0.5
              TOPK_CANDIDATES_TEST: 400
              NMS_THRESH_TEST: 0.45
              BBOX_REG_WEIGHTS: [10.0, 10.0, 5.0, 5.0]
              MULTIBOX_LOSS_NEG_POS_RATIO: 1.0
          ANCHOR_GENERATOR:
            NAME: "SSDAnchorGenerator"
            SIZES: [[30.0], [60.0], [111.0]]
            ASPECT_RATIOS: [[1.0, 2.0, 0.5], [1.0, 2.0, 0.5, 3.0, 0.3333333]]
            OFFSET: 0.5
      LOSS_WEIGHT: 1.0
    CLASSIFIER:
      MODULE: 'backbone'
      TYPE: 'MobileNetV3'
      KWARGS:
        pretrained: True
        num_classes: 12
      LOSS_WEIGHT: 1.0
SOLVER:
  BASE_LR: 0.0005
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  GAMMA: 0.1
  IMS_PER_BATCH: 12
  MAX_ITER: 1000000
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: ./results
